### ISSUE TITLE
Cannot be installed on window.

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#1]
This kanbun can not be installed on window. I installed it in window and it didn't work. Is there any way to fix it?

**Comment by KoichiYasuoka** [comment]
Sorry @niutyut but please use Cygwin as shown in [Installation for Cygwin](https://github.com/KoichiYasuoka/UD-Kanbun#installation-for-cygwin). 64-bit version is recommended but 32-bit can work.
