### ISSUE TITLE
about Installation for Jupyter Notebook

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#2]
My system is window and I am using Jupyter Notebook with Anaconda3 (64-bit). Can I install UD-kanbun?
Because I see that the installation needs to be in google environment. I can't connect to google cloud service here.
If i install kanbun  under window, and  want to use Jupyter Notebook, how do i do it?thank you

**Comment by KoichiYasuoka** [comment]
>My system is window and I am using Jupyter Notebook with Anaconda3 (64-bit). Can I install UD-kanbun?

Sorry but I could not. Please use Cygwin as I mentioned in #1.
