### ISSUE TITLE
Under cygwin environment, udkanbun cannot be installed

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#3]
Under cygwin environment, udkanbun cannot be installed. here are these installation errors. Do you see what the problem is?

ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h4rmips8/ufal-udpipe_ce2abc4ddd534f60ac34cae07d34d71d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h4rmips8/ufal-udpipe_ce2abc4ddd534f60ac34cae07d34d71d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jj9r2fb7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.7m/ufal.udpipe
         cwd: /tmp/pip-install-h4rmips8/ufal-udpipe_ce2abc4ddd534f60ac34cae07d34d71d/
    Complete output (16 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.cygwin-3.2.0-x86_64-3.7
    creating build/lib.cygwin-3.2.0-x86_64-3.7/ufal
    copying ufal/__init__.py -> build/lib.cygwin-3.2.0-x86_64-3.7/ufal
    copying ufal/udpipe.py -> build/lib.cygwin-3.2.0-x86_64-3.7/ufal
    running build_ext
    building 'ufal._udpipe' extension
    creating build/temp.cygwin-3.2.0-x86_64-3.7
    creating build/temp.cygwin-3.2.0-x86_64-3.7/udpipe
    gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/pub/devel/python/python37/python37-3.7.10-2.x86_64/build=/usr/src/debug/python37-3.7.10-2 -fdebug-prefix-map=/pub/devel/python/python37/python37-3.7.10-2.x86_64/src/Python-3.7.10=/usr/src/debug/python37-3.7.10-2 -ggdb -O2 -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector-strong --param=ssp-buffer-size=4 -fdebug-prefix-map=/pub/devel/python/python37/python37-3.7.10-2.x86_64/build=/usr/src/debug/python37-3.7.10-2 -fdebug-prefix-map=/pub/devel/python/python37/python37-3.7.10-2.x86_64/src/Python-3.7.10=/usr/src/debug/python37-3.7.10-2 -Iudpipe/include -I/usr/include/python3.7m -c udpipe/udpipe.cpp -o build/temp.cygwin-3.2.0-x86_64-3.7/udpipe/udpipe.o -std=c++11 -fvisibility=hidden -w
    gcc: fatal error: cannot execute ‘cc1plus’: spawn: No such file or directory
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.7 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h4rmips8/ufal-udpipe_ce2abc4ddd534f60ac34cae07d34d71d/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h4rmips8/ufal-udpipe_ce2abc4ddd534f60ac34cae07d34d71d/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jj9r2fb7/install-record.txt --single-version-externally-managed --compile --install-headers /usr/include/python3.7m/ufal.udpipe Check the logs for full command output.

**Comment by KoichiYasuoka** [comment]
```
gcc: fatal error: cannot execute ‘cc1plus’: spawn: No such file or directory
```

means that your Cygwin does not have proper version of `g++`. Try to re-install `gcc-g++` package again, updating Cygwin packages. Then check the versions of `gcc` and `g++` with the two commands shown below:

```
gcc --version
g++ --version
```

**Comment by KoichiYasuoka** [comment]
Please use single issue, and don't make another issue #4.

**Comment by KoichiYasuoka** [comment]
Well @niutyut, you have to read https://github.com/KoichiYasuoka/UD-Kanbun#installation-for-cygwin more careful. And you should keep the single issue https://github.com/KoichiYasuoka/UD-Kanbun/issues/3 to make consequent questions.

**Comment by niutyut** [comment]
i finish installation.thank you!
![image](https://user-images.githubusercontent.com/7684989/131762034-a5e5d9f9-d967-44a2-9f09-e463f5716f1e.png)
