### ISSUE TITLE
Unsuccessful installation

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#4]
I have installed the gcc-g++ python37-pip python37-devel packages，but it is unsuccessful

![image](https://user-images.githubusercontent.com/7684989/131687323-fe8017cc-7dbe-4a30-a712-cf90add85fa0.png)

**Comment by KoichiYasuoka** [comment]
It seems that you use `pip` of Windows instead of `pip3.7` of Cygwin. Please use `pip3.7` and `python3.7` on Cygwin.

**Comment by KoichiYasuoka** [comment]
Please use single issue #3, and don't make another issue here @niutyut.
