### ISSUE TITLE
save  s as a txt file or a csv file

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#5]
hello,
Can you tell me how to save the generated results as a txt file or a csv file? Thank you!
![image](https://user-images.githubusercontent.com/7684989/133597930-9204a618-7759-4cae-8926-0eb8b2ef58f9.png)

**Comment by niutyut** [comment]
If I have a Chinese txt file, how can it be executed by your package by opening the file?
s=lzh(file),this file come from local file ,for example 三国演义.txt is in D:\, how to use this file?

**Comment by KoichiYasuoka** [comment]
You can use `open` of python:

```
>>> import udkanbun
>>> lzh=udkanbun.load()
>>> fi=open("input.txt","r",encoding="utf-8")
>>> fo=open("output.txt","w",encoding="utf-8")
>>> s=lzh(fi.read())
>>> print(s,file=fo)
>>> fi.close()
>>> fo.close()
```

I think that the filename should be in ASCII (not 三国演义.txt) and should not be much bigger.
