### ISSUE TITLE
extract the nouns

### ISSUE THREAD

**Issue by niutyut** [KoichiYasuoka/UD-Kanbun#6]
hello,
 I want to extract the nouns from and now execute a txt file of about 400k. But the execution time for selecting nouns is very long. Is there a better function to achieve this noun extraction? Because the package you have given does not have the documentation of the function. So I can only ask you here. Here is the program I wrote to extract the nouns.

fname="E:\\知识图谱\\撰写论文\\编程思路进展\\word2vec\\R语言\\corpus\\"+file+"\\pooled.txt"
    with open(fname, 'r+', encoding='utf-8') as fi:
        s = [i.split(',')[1].replace("\n","") for i in fi.readlines()]
    str1=''.join(s)     
    fo_name="E:\\知识图谱\\撰写论文\\编程思路进展\\word2vec\\R语言\\corpus\\"+file+"\\pooled_NOUN.txt"
    fo=open(fo_name,"w",encoding="utf-8")
    s=lzh(str1)
    select_NOUN=[]
    for i in range(len(s)):
        t=s[i]
        if t.upos=="NOUN":
            select_NOUN.append(t.form) 
    str2=' '.join(select_NOUN)  
    fo.write(str2) 
    fi.close()        
    fo.close()

**Comment by KoichiYasuoka** [comment]
Hi @niutyut

>I want to extract the nouns from and now execute a txt file of about 400k. But the execution time for selecting nouns is very long.

I think you need more powerful machine. Then, I recommend you to use [roberta-classical-chinese-base-upos](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-upos) or  [roberta-classical-chinese-large-upos](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-upos) if you need only POS-tagging without dependency-parsing.

**Comment by niutyut** [comment]
roberta-classical-chinese-base-upos or roberta-classical-chinese-large-upos ，how to download these files？please give me web address，thank you！ 
import torch
from transformers import AutoTokenizer,AutoModelForTokenClassification
tokenizer=AutoTokenizer.from_pretrained("KoichiYasuoka/roberta-classical-chinese-base-upos")
model=AutoModelForTokenClassification.from_pretrained("KoichiYasuoka/roberta-classical-chinese-base-upos")
s="子曰學而時習之不亦説乎有朋自遠方來不亦樂乎人不知而不慍不亦君子乎"
p=[model.config.id2label[q] for q in torch.argmax(model(tokenizer.encode(s,return_tensors="pt"))[0],dim=2)[0].tolist()[1:-1]]
print(list(zip(s,p)))

![image](https://user-images.githubusercontent.com/7684989/133977500-9cba2b33-7152-4f61-90f7-a9bfc68a29b2.png)

**Comment by KoichiYasuoka** [comment]
>roberta-classical-chinese-base-upos or roberta-classical-chinese-large-upos ，how to download these files？

The necessary files are automatically downloaded by `transformers`. If you directly download them from https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-upos/tree/main or https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-upos/tree/main then you should directly use them with `from_pretrained` module, but I'm vague how to use them directly in your machine.

**Comment by niutyut** [comment]
fname="E:\\知识图谱\\撰写论文\\编程思路进展\\word2vec\\R语言\\corpus\\"+file+"\\pooled.txt"
    with open(fname, 'r+', encoding='utf-8') as fi:
        s = [i.split(',')[1].replace("\n","") for i in fi.readlines()]
    str1=str(''.join(s).replace(" ", ""))
 
    fo_name="E:\\知识图谱\\撰写论文\\编程思路进展\\word2vec\\R语言\\corpus\\"+file+"\\pooled_NOUN_new.txt"
    fo=open(fo_name,"w",encoding="utf-8")
    p=[model.config.id2label[q] for q in torch.argmax(model(tokenizer.encode(str1,return_tensors="pt"))[0],dim=2)[0].tolist()[1:-1]]
    print(list(zip(str1,p)))
   

error is below.
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

I read the text file for calculation . I have a text file of about tens of thousands of words! What is this to do?

**Comment by KoichiYasuoka** [comment]
I think that the text is too large, maybe more than 256 characters. Cut the text into the list of sentences, and use `torch.argmax` with every sentence one by one.
