### ISSUE TITLE
How can I get a sentence list with Danku?

### ISSUE THREAD

**Issue by ByungjunKim** [KoichiYasuoka/UD-Kanbun#7]
Hello, I am a lecturer in South Korea.

Kanbun package is amazing! Thank you for sharing your package.

I want to get a sentence list with Danku parameter.
WIth Danku, I get segmentation, however, I want to return chunk list like below.

```
lzh=udkanbun.load(Danku=True)
s=lzh("孟子對曰, 王! 何必曰利? 亦有仁義而已矣")
```

-> ['孟子對曰,', '王! 何必曰利?', '亦有仁義而已矣']

**Comment by KoichiYasuoka** [comment]
Punctuations were not used in Classical Chinese, so as UD-Kanbun:

```
>>> import udkanbun
>>> lzh=udkanbun.load(Danku=True)
>>> s=lzh("孟子對曰王何必曰利亦有仁義而已矣")
>>> print(s)
# text = 孟子對曰
1	孟子	孟子	PROPN	n,名詞,人,複合的人名	NameType=Prs	3	nsubj	_	Gloss=Mencius|SpaceAfter=No
2	對	對	VERB	v,動詞,行為,伝達	_	3	advmod	_	Gloss=reply|SpaceAfter=No|Translit=对
3	曰	曰	VERB	v,動詞,行為,伝達	_	0	root	_	Gloss=say|SpaceAfter=No

# text = 王何必曰利
1	王	王	NOUN	n,名詞,人,役割	_	4	nsubj	_	Gloss=king|SpaceAfter=No
2	何	何	ADV	v,副詞,疑問,原因	AdvType=Cau	4	advmod	_	Gloss=what|SpaceAfter=No
3	必	必	ADV	v,副詞,判断,確定	_	4	advmod	_	Gloss=necessarily|SpaceAfter=No
4	曰	曰	VERB	v,動詞,行為,伝達	_	0	root	_	Gloss=say|SpaceAfter=No
5	利	利	NOUN	n,名詞,描写,形質	_	4	obj	_	Gloss=profit|SpaceAfter=No

# text = 亦有仁義而已矣
1	亦	亦	ADV	v,副詞,頻度,重複	_	2	advmod	_	Gloss=also|SpaceAfter=No
2	有	有	VERB	v,動詞,存在,存在	_	0	root	_	Gloss=have|SpaceAfter=No
3	仁	仁	NOUN	n,名詞,描写,態度	_	2	obj	_	Gloss=benevolence|SpaceAfter=No
4	義	義	NOUN	n,名詞,描写,態度	_	3	conj	_	Gloss=righteousness|SpaceAfter=No|Translit=义
5	而	而	PART	p,助詞,句末,*	_	2	discourse:sp	_	Gloss=and|SpaceAfter=No
6	已	已	PART	p,助詞,句末,*	_	2	discourse:sp	_	Gloss=only|SpaceAfter=No
7	矣	矣	PART	p,助詞,句末,*	_	2	discourse:sp	_	Gloss=[PFV]|SpaceAfter=No

```

Now you can get three sentences in `str(s)`. It is very easy to `split` them:

```
>>> t=[x[9:] for x in str(s).split("\n") if x.startswith("# text = ")]
>>> print(t)
['孟子對曰', '王何必曰利', '亦有仁義而已矣']
```

**Comment by ByungjunKim** [comment]
Thank you, professor!

**Comment by KoichiYasuoka** [comment]
But I recommend you @ByungjunKim to use [roberba-classical-chinese-base-sentence-segmentation](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-base-sentence-segmentation) or [roberba-classical-chinese-large-sentence-segmentation](https://huggingface.co/KoichiYasuoka/roberta-classical-chinese-large-sentence-segmentation) if you only want sentence-segmentation (Danku) without POS-tagging or dependency-parsing.

**Comment by ByungjunKim** [comment]
If I want tokenizer with BERT model, is it right to use SuPar-Kanbun? 
I think that UD-Kanbun is not based on BERT model.

I belong to Sungkyunkwan University, and I will employ your packages for analyzing Confucian classics.
Your packages are awesome!

**Comment by KoichiYasuoka** [comment]
[SuPar-Kanbun](https://github.com/KoichiYasuoka/SuPar-Kanbun) is based on BERT/RoBERTa models. UD-Kanbun is based on rather old packages: [MeCab](https://pypi.org/project/mecab-python3) and [UDPipe](https://pypi.org/project/ufal.udpipe).
