### ISSUE TITLE
Splitting 2-character words by space?

### ISSUE THREAD

**Issue by James-G-Hill** [KoichiYasuoka/UD-Kanbun#8]
Hello, I tried analysing the following phrase:

`乃夫子也吾貺子`

It identified '夫子' as a single noun ('master' or 'Confucius') whereas in this phrase I believe that it is a demonstrative pronoun followed by a pronoun?

Then I tried:

`乃夫 子也吾貺子`

with a space between '夫' and '子'; this separates out the characters into 2 nouns (which I think is still incorrect, but I guess better?)

So I just wanted to check, is adding a space between characters the correct method to split 2-character words when they shouldn't be?
Or have I just come across a bug?

Here's a link to the mini-project I'm working on if you want some context; it's just for self-learning:
https://github.com/James-G-Hill/Notes_to_Outline_of_Classical_Chinese_Grammar/blob/master/ch3_noun_predication.ipynb

**Comment by KoichiYasuoka** [comment]
Well @James-G-Hill that wording of 夫子 comes from [UD_Classical-Chinese-Kyoto](https://github.com/UniversalDependencies/UD_Classical_chinese-Kyoto). In the project we regard 夫子 as one word all through the UD corpus. Thus, if you need to split 夫子 into two words, you need to make another UD corpus to build another tokenizer.

**Comment by KoichiYasuoka** [comment]
I've just written a tentative code on Google Colaboratory to get a UDPipe model which splits 夫子 into two words:

```
!test -f udpipe-1.2.0-bin.zip || curl -LO https://github.com/ufal/udpipe/releases/download/v1.2.0/udpipe-1.2.0-bin.zip
!test -d udpipe-1.2.0-bin || unzip udpipe-1.2.0-bin.zip
!test -f /usr/local/bin/udpipe || cp udpipe-1.2.0-bin/bin-linux64/udpipe /usr/local/bin/udpipe && chmod 755 /usr/local/bin/udpipe
!test -d UD_Classical_Chinese-Kyoto || git clone --depth=1 https://github.com/UniversalDependencies/UD_Classical_Chinese-Kyoto
with open("UD_Classical_Chinese-Kyoto/lzh_kyoto-ud-train.conllu","r",encoding="utf-8") as f:
  r=f.read()
with open("train.conllu","w",encoding="utf-8") as f:
  for s in r.split("\n\n"):
    c=[]
    for t in s.split("\n"):
      if t.startswith("#"):
        print(t,file=f)
      else:
        w=t.split("\t")
        if len(w)==10 and w[0].isdecimal():
          c.append(w)
    for v in reversed(range(len(c))):
      w=list(c[v])
      if w[1]=="夫子":
        c[v]=["_","夫","夫","PRON","_","_",w[0],"det","_","SpaceAfter=No"]
        c.insert(v+1,["_","子","子","PRON","_","_",w[6],w[7],"_","SpaceAfter=No"])
        for i,j in enumerate(c):
          j[0]=str(i+1)
          k=int(j[6])
          j[6]=str(k+1 if k>v else k)
    print("\n".join("\t".join(w) for w in c),file=f,end="\n\n")
!test -f my.udpipe || udpipe --train my.udpipe train.conllu
```

In three hours or less you can get `my.udpipe` which includes the tokenizer you need. Now you can use it via UD-Kanbun:

```
!pip install udkanbun
import udkanbun
lzh=udkanbun.UDKanbun(mecab=False,danku=False,model="my.udpipe")
s=lzh("乃夫子也吾貺子")
print(s)
```

But the code is too tentative, thus @James-G-Hill you need to tune it up for your own purpose.

**Comment by James-G-Hill** [comment]
Thanks.  I'm still curious though, am I correct that in my example '夫' and '子' are separate words?  I guess if that's the case then the corpus just doesn't have any examples of sentences where they should be treated separately?

Or is the tokenizer not capable of understanding when pairs of characters should be treated as a dual word or 2 separate words depending on context?

**Comment by James-G-Hill** [comment]
I appreciate all of the help too; I realise I've asked a lot of questions this last couple of weeks.

**Comment by KoichiYasuoka** [comment]
In [our trials](http://kanji.zinbun.kyoto-u.ac.jp/~yasuoka/publications/diccs2018.pdf) of dependency-parsing of classical Chinese texts, we considered that 孟子 seems to be one word, not two words. On the other hand 天子 should consist of two words 天 and 子. Then how about 君子? How about 夫子? We decided 君子 as one word, so as 夫子, in practical reason (due to the power of Conditional Random Fields as described in [our paper](http://id.nii.ac.jp/1001/00185742/)). So I understand that 夫子 is regarded as two words  in some other point of view.

And now we are developing our new package [SuPar-Kanbun](https://github.com/KoichiYasuoka/SuPar-Kanbun), in which BERT/RoBERTa models (trained by all texts of 四庫全書) are used to determine the word boundaries and the sentence boundaries.

**Comment by KoichiYasuoka** [comment]
And now we try to use BERT/RoBERTa models (trained by all texts of 四庫全書) to determine the word boundaries and the sentence boundaries in our new package [SuPar-Kanbun](https://github.com/KoichiYasuoka/SuPar-Kanbun).

**Comment by James-G-Hill** [comment]
Thanks for the references; I will read them where I can.

**Comment by James-G-Hill** [comment]
Started using SuPar-Kanbun with the BERT model you provide as default and the dependency parsing is noticeably superior to UD-Kanbun so would recommend that to anyone else wondering whether to make the switch.
